##################################################################################################
# Config service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: samples-config-service
  namespace: flomesh-spring
  labels:
    app: config
    service: samples-config-service
spec:
  ports:
    - port: 8888
      name: http
      targetPort: 8888
  selector:
    app: config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: samples-config-service-v1
  namespace: flomesh-spring
  labels:
    app: config
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config
      version: v1
  template:
    metadata:
      labels:
        app: config
        version: v1
        service: samples-config-service
      annotations:
        service.flomesh.io/name: "samples-config-service"
    spec:
      initContainers:
        - name: check-discovery
          image: busybox:latest
          command: ["/bin/sh", "-c"]
          args:
            - |-
              until nc -vz samples-discovery-server 8761; \
                do echo "Waiting for Eureka ready ..."; \
                sleep 5; \
              done;
      containers:
        - name: app
          image: docker.io/flomesh/samples-config-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8888
          env:
            - name: K8S_SAMPLES_DISCOVERY_SERVER_HOSTNAME
              value: samples-discovery-server
            - name: K8S_SAMPLES_DISCOVERY_SERVER_PORT
              value: "8771"
            - name: K8S_SAMPLES_BOOKINFO_RATINGS_HOSTNAME
              value: samples-bookinfo-ratings
            - name: K8S_SERVICE_NAME
              value: samples-config-service
            - name: _samples_pod_ns
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: _samples_pod_nodeName
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: _samples_pod_name
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: _samples_pod_serviceName
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['service']
            - name: _samples_pod_serviceVersion
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['version']
            - name: _samples_pod_serviceFullName
              value: $(_samples_pod_serviceName)-$(_samples_pod_serviceVersion)
            - name: _samples_pod_UID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
            - name: _samples_pod_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: _samples_pod_hostIP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          resources:
            limits:
              memory: 600Mi
            requests:
              memory: 300Mi