create table log (
    rid UInt64 default JSONExtractInt(message,'rid'),
    sid UInt64 default JSONExtractInt(message,'sid'),
    iid String default JSONExtractString(message,'iid'),
    dir String default JSONExtractString(message,'dir'),
    proto String default JSONExtractString(message,'proto'),
    req String default JSONExtractRaw(message,'req'),
    `req.id` String default JSONExtractString(req,'id'),
    `req.protocol` String default JSONExtractString(req,'protocol'),
    `req.version` String default JSONExtractString(req,'version'),
    `req.service.name` String default JSONExtractString(req,'service.name'),
    `req.service.version` String default JSONExtractString(req,'service.version'),
    `req.method.name` String default JSONExtractString(req,'method.name'),
    `req.method.type` String default JSONExtractString(req,'method.type'),
    `req.method` String default JSONExtractString(req,'method'),
    `req.path` String default JSONExtractString(req,'path'),
    `req.headers` String default JSONExtractRaw(req,'headers'),
    `req.body` String default JSONExtractString(req,'body'),
    `req.arguments` Array(String) default JSONExtractArrayRaw(req,'arguments'),
    res String default JSONExtractRaw(message,'res'),
    `res.protocol` String default JSONExtractString(res,'protocol'),
    `res.type` Int32 default JSONExtractInt(res,'type'),
    `res.value` String default JSONExtractString(res,'value'),
    `res.status` UInt32 default JSONExtractInt(res,'status'),
    `res.statusText` String default JSONExtractString(res,'statusText'),
    `res.headers` String default JSONExtractRaw(res,'headers'),
    `res.body` String default JSONExtractString(res,'body'),
    reqTime UInt64 default JSONExtractInt(message,'reqTime'),
    resTime UInt64 default JSONExtractInt(message,'resTime'),
    reqSize UInt64 default JSONExtractInt(message,'reqSize'),
    resSize UInt64 default JSONExtractInt(message,'resSize'),
    localAddr String default JSONExtractString(message, 'localAddr'),
    localPort UInt32 default JSONExtractInt(message, 'localPort'),
    remoteAddr String default JSONExtractString(message, 'remoteAddr'),
    remotePort UInt32 default JSONExtractInt(message, 'remotePort'),
    node String default JSONExtractRaw(message,'node'),
    `node.ip` String default JSONExtractString(node,'ip'),
    `node.name` String default JSONExtractString(node,'name'),
    pod String default JSONExtractRaw(message,'pod'),
    `pod.ns` String default JSONExtractString(pod,'ns'),
    `pod.ip` String default JSONExtractString(pod,'ip'),
    `pod.name` String default JSONExtractString(pod,'name'),
    service String default JSONExtractRaw(message,'service'),
    `service.name` String default JSONExtractString(service,'name'),
    target String default JSONExtractRaw(message,'target'),
    `target.address` String default JSONExtractString(target,'address'),
    `target.port` UInt32 default JSONExtractInt(target,'port'),
    trace String default JSONExtractRaw(message,'trace'),
    `trace.id` String default JSONExtractString(trace,'id'),
    `trace.span` String default JSONExtractString(trace,'span'),
    `trace.parent` String default JSONExtractString(trace,'parent'),
    `trace.sampled` String default JSONExtractString(trace,'sampled'),
    `env` String DEFAULT JSONExtractRaw(message, 'env'),
    id UUID default generateUUIDv4(),
    targetId UUID,
    timestamp DateTime default now(),
    message String
) engine=MergeTree()
partition by toYYYYMM(toDateTime(reqTime/1000))
order by reqTime;
